name: Unit testing for npoi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          '3.1.x', '6.0.x'

    - name: Restore NPOI.Core.Test dependencies
      run: dotnet restore solution/NPOI.Core.Test.sln
    - name: Build NPOI.Core.Test
      run: dotnet build solution/NPOI.Core.Test.sln --no-restore --configuration 'Debug' --verbosity n
    - name: Test NPOI.Core.Test
      run: dotnet test solution/NPOI.Core.Test.sln --no-build --configuration 'Debug' --verbosity normal
    
    - name: Restore NPOI.Test dependencies
      run: dotnet restore solution/NPOI.Test.sln
    - name: Build NPOI.Test
      run: dotnet build solution/NPOI.Test.sln --no-restore --configuration 'Debug' --verbosity n
    - name: Test NPOI.Test
      run: dotnet test solution/NPOI.Test.sln --no-build --configuration 'Debug' --verbosity normal

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: "**/*.xml"
