name: Unit testing for NPOI.Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 3.1.x
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 6.0.x

    - name: Restore NPOI.Core.Test dependencies
      run: dotnet restore solution/NPOI.Core.Test.sln
    - name: Build NPOI.Core.Test
      run: dotnet build solution/NPOI.Core.Test.sln --no-restore --configuration 'Debug' --verbosity n
    - name: Test NPOI.Core.Test
      run: dotnet test solution/NPOI.Core.Test.sln --no-build --configuration 'Debug' --verbosity n --logger trx --results-directory test-results

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        path: 'test-results/*.trx'
        name: Test Results
        reporter: 'dotnet-trx'
