name: Unit testing for npoi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore solution/NPOI.Core.Test.sln
    - name: Build
      run: dotnet build solution/NPOI.Core.Test.sln --no-restore --configuration 'Debug' --verbosity n
    - name: Test
      run: dotnet test solution/NPOI.Core.Test.sln --no-build --configuration 'Debug' --verbosity normal
    
    - name: Restore dependencies
      run: dotnet restore solution/NPOI.Test.sln
    - name: Build
      run: dotnet build solution/NPOI.Test.sln --no-restore --configuration 'Debug' --verbosity n
    - name: Test
      run: dotnet test solution/NPOI.Test.sln --no-build --configuration 'Debug' --verbosity normal
